exclude: ^tests/testdata/

repos:
    - repo: https://github.com/pre-commit/pre-commit-hooks
      rev: v6.0.0
      hooks:
          - id: check-yaml
          - id: end-of-file-fixer
          - id: trailing-whitespace
    - repo: local
      hooks:
          - id: black
            name: black
            entry: uv run --no-sync black
            language: system
            types: [python]
          - id: flake8
            name: flake8
            entry: uv run --no-sync flake8
            language: system
            types: [python]
