name: uv ci

on:
  pull_request:

jobs:
  build:
    strategy:
      matrix:
        os: ["ubuntu-latest", "windows-latest"]
    defaults:
      run:
        shell: bash
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out repository
        uses: actions/checkout@v7
      - name: Install uv
        uses: astral-sh/setup-uv@v10.2.0
        with:
          enable-cache: true
          cache-dependency-glob: "uv.lock"
      - name: Set up python
        run: uv python install
      - name: Install dependencies
        run: uv sync --locked --dev
      - name: Run tests
        run: uv run pytest
      - name: Lint
        run: uv run flake8 . || echo "Linting errors found, but we're treating this as a warning."
      - name: Format
        run: uv run black . --check || echo "Formatting errors found, but we're treating this as a warning."
